<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.0.22.47 SP?>
<Program xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File>README.txt</File>
    <File Private="true">testSuite.var</File>
    <File Description="Handling of program and test suite">testSuite.c</File>
    <File Description="Auto generated code">autoGeneratedFile.c</File>
    <File Description="Variables used in testSet_Asserts" Private="true">varAsserts.var</File>
    <File Description="Available Asserts">testSet_Asserts.c</File>
  </Files>
</Program>