<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.0.20.56 SP?>
<Program xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="Name the suite and add PVs for the program" Private="true">variables.var</File>
    <File>testSuite.c</File>
    <File Description="Auto generated code - list of all test sets in the program">autoGeneratedFile.c</File>
  </Files>
</Program>