
ACTION AlarmHandling: 

    // CommissioningModeActive will inhibit Alarms[0], see mpAlarmX configuration (must enable Advanced Features)
    // CommissioningModeActive = TRUE will inhibit Alarms[0], = FALSE will NOT inhibit Alarms[0]
    CommissioningModeActive;
    
    Alarms[0];
//    Alarms[1] := ;
//    Alarms[2] := ;
//    Alarms[3] := ;
//    Alarms[4] := ;
//    Alarms[5] := ;
//    Alarms[6] := ;
//    Alarms[7] := ;
//    Alarms[8] := ;
//    Alarms[9] := ;
//    
//    Alarms[10] := ;
//    Alarms[11] := ;
//    Alarms[12] := ;
//    Alarms[13] := ;
//    Alarms[14] := ;
//    Alarms[15] := ;
//    Alarms[16] := ;
//    Alarms[17] := ;
//    Alarms[18] := ;
//    Alarms[19] := ;

END_ACTION
