ACTION AlarmHandling:

    // CommissioningModeActive = TRUE will inhibit Alarms[0]. The alarm will not trigger even if the alarm condition is active.
	// CommissioningModeActive = FALSE will NOT inhibit Alarms[0]. The alarm will trigger when the alarm condition is active.
	// See Alarm.mpalarmxcore (must enable Advanced Features)
    CommissioningModeActive;
    
	// Define the condition which triggers each alarm below.
	Alarms[0];

//    Alarms[1] := ;
//    Alarms[2] := ;
//    Alarms[3] := ;
//    Alarms[4] := ;
//    Alarms[5] := ;
//    Alarms[6] := ;
//    Alarms[7] := ;
//    Alarms[8] := ;
//    Alarms[9] := ;
//
//    Alarms[10] := ;
//    Alarms[11] := ;
//    Alarms[12] := ;
//    Alarms[13] := ;
//    Alarms[14] := ;
//    Alarms[15] := ;
//    Alarms[16] := ;
//    Alarms[17] := ;
//    Alarms[18] := ;
//    Alarms[19] := ;
//
//    Alarms[20] := ;
//    Alarms[21] := ;
//    Alarms[22] := ;
//    Alarms[23] := ;
//    Alarms[24] := ;
//    Alarms[25] := ;
//    Alarms[26] := ;
//    Alarms[27] := ;
//    Alarms[28] := ;
//    Alarms[29] := ;
//
//    Alarms[30] := ;
//    Alarms[31] := ;
//    Alarms[32] := ;
//    Alarms[33] := ;
//    Alarms[34] := ;
//    Alarms[35] := ;
//    Alarms[36] := ;
//    Alarms[37] := ;
//    Alarms[38] := ;
//    Alarms[39] := ;
//
//    Alarms[40] := ;
//    Alarms[41] := ;
//    Alarms[42] := ;
//    Alarms[43] := ;
//    Alarms[44] := ;
//    Alarms[45] := ;
//    Alarms[46] := ;
//    Alarms[47] := ;
//    Alarms[48] := ;
//    Alarms[49] := ;
//
//    Alarms[50] := ;
//    Alarms[51] := ;
//    Alarms[52] := ;
//    Alarms[53] := ;
//    Alarms[54] := ;
//    Alarms[55] := ;
//    Alarms[56] := ;
//    Alarms[57] := ;
//    Alarms[58] := ;
//    Alarms[59] := ;
//
//    Alarms[60] := ;
//    Alarms[61] := ;
//    Alarms[62] := ;
//    Alarms[63] := ;
//    Alarms[64] := ;
//    Alarms[65] := ;
//    Alarms[66] := ;
//    Alarms[67] := ;
//    Alarms[68] := ;
//    Alarms[69] := ;
//
//    Alarms[70] := ;
//    Alarms[71] := ;
//    Alarms[72] := ;
//    Alarms[73] := ;
//    Alarms[74] := ;
//    Alarms[75] := ;
//    Alarms[76] := ;
//    Alarms[77] := ;
//    Alarms[78] := ;
//    Alarms[79] := ;
//
//    Alarms[80] := ;
//    Alarms[81] := ;
//    Alarms[82] := ;
//    Alarms[83] := ;
//    Alarms[84] := ;
//    Alarms[85] := ;
//    Alarms[86] := ;
//    Alarms[87] := ;
//    Alarms[88] := ;
//    Alarms[89] := ;
//
//    Alarms[90] := ;
//    Alarms[91] := ;
//    Alarms[92] := ;
//    Alarms[93] := ;
//    Alarms[94] := ;
//    Alarms[95] := ;
//    Alarms[96] := ;
//    Alarms[97] := ;
//    Alarms[98] := ;
//    Alarms[99] := ;

END_ACTION
