<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Private="true">TestType.typ</File>
    <File Description="Name the suite and add PVs for the program" Private="true">variables.var</File>
    <File>testSuite.c</File>
    <File>Set_SetupTeardown.c</File>
    <File Description="Auto generated code - list of all test sets in the program">autoGeneratedFile.c</File>
    <File Description="Local data types" Private="true" Reference="true">\Logical\MachineControl\AxisTemplate\AxisMgr\AxisMgr.typ</File>
  </Files>
</Program>