<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.2.1.211?>
<Program xmlns="http://br-automation.co.at/AS/Program" Description="This sample is about the control flow of test programs">
  <Objects>
    <Object Type="File">README.txt</Object>
    <Object Type="File" Private="true">testSuite.var</Object>
    <Object Type="File" Description="Handling of program and test suite">testSuite.c</Object>
    <Object Type="File" Description="Auto generated code">autoGeneratedFile.c</Object>
    <Object Type="File">iPrototypes.h</Object>
    <Object Type="File">iHelperFunction.h</Object>
    <Object Type="File">iHelperFunction.c</Object>
    <Object Type="File" Description="Variables used in sub package &quot;ControlFlow&quot;" Private="true">controlFlowVariables.var</Object>
    <Object Type="Package" Description="Shows sequence of calls within test set (depending on the defined optional handles)">ControlFlow</Object>
    <Object Type="File" Description="Variables used in sub package &quot;TestBusy_Asyncronous&quot;" Private="true">TestBusy_AsyncronousVariables.var</Object>
    <Object Type="Package" Description="Testing FBs / testing with a busy condition">TestBusy_Asyncronous</Object>
  </Objects>
</Program>