<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.0.22.47 SP?>
<Program xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="PVs for the program and test suite" Private="true">variables.var</File>
    <File Description="Handling of program and test suite">testSuite.c</File>
    <File Description="Auto generated code">autoGeneratedFile.c</File>
    <File Description="Groups test cases for substraction">testSet_MyCalcLib_Subtraction.c</File>
    <File Description=" To check multiple subtraction combinations without code duplication a helper function can be created.">testSet_MyCalcLib_Subtraction_variantA.c</File>
    <File Description="TEST_ASSERT is used to output the parameters passed to the helper function when helper returns a failed.">testSet_MyCalcLib_Subtraction_variantB.c</File>
    <File Description="When the helper is formulated as macro, the correct location (line / file) inside the testcase is given.">testSet_MyCalcLib_Subtraction_variantC.c</File>
    <File Description="Custom Assert">testSet_MyCalcLib_Subtraction_variantD.c</File>
  </Files>
</Program>