
ACTION HmiCommands:
	
	MpPackMLMode_0.Abort := HmiPackML.Commands.Abort;
	MpPackMLMode_0.Clear := HmiPackML.Commands.Clear;
	MpPackMLMode_0.StateComplete := HmiPackML.Commands.Complete;
	MpPackMLMode_0.Hold := HmiPackML.Commands.Hold;
	MpPackMLMode_0.Reset := HmiPackML.Commands.Reset;
	MpPackMLMode_0.Start := HmiPackML.Commands.Start;
	MpPackMLMode_0.Stop := HmiPackML.Commands.Stop;
	MpPackMLMode_0.Suspend := HmiPackML.Commands.Suspend;
	MpPackMLMode_0.Unhold := HmiPackML.Commands.Unhold;
	MpPackMLMode_0.Unsuspend := HmiPackML.Commands.Unsuspend;

END_ACTION
	

