
ACTION HmiCommands:
	
	MpPackMLModule_Main.Command.Abort := HmiPackML.Commands.Abort;
	MpPackMLModule_Main.Command.Clear := HmiPackML.Commands.Clear;
	MpPackMLModule_Main.Command.StateComplete := HmiPackML.Commands.Complete;
	MpPackMLModule_Main.Command.Hold := HmiPackML.Commands.Hold;
	MpPackMLModule_Main.Command.Reset := HmiPackML.Commands.Reset;
	MpPackMLModule_Main.Command.Start := HmiPackML.Commands.Start;
	MpPackMLModule_Main.Command.Stop := HmiPackML.Commands.Stop;
	MpPackMLModule_Main.Command.Suspend := HmiPackML.Commands.Suspend;
	MpPackMLModule_Main.Command.Unhold := HmiPackML.Commands.Unhold;
	MpPackMLModule_Main.Command.Unsuspend := HmiPackML.Commands.Unsuspend;

END_ACTION
	

