<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="Local data types" Private="true" Reference="true">\Logical\Infrastructure\Recipe\RecipeMgr\RecipeMgr.typ</File>
    <File Description="Local variables" Private="true" Reference="true">\Logical\Infrastructure\Recipe\RecipeMgr\RecipeMgr.var</File>
    <File Description="Name the suite and add PVs for the program" Private="true">variables.var</File>
    <File>testSuite.c</File>
    <File Description="Auto generated code - list of all test sets in the program">autoGeneratedFile.c</File>
    <File>Set_RecipeMgr.c</File>
    <File Description="Name the suite and add PVs for the program" Private="true" Reference="true">\Logical\UnitTest\Common\CommonUT\CommonVariables.var</File>
    <File Reference="true">\Logical\UnitTest\Common\CommonUT\Set_Common.c</File>
  </Files>
</Program>