<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio Version=4.0.22.47 SP?>
<Program xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="PVs for the program and test suite" Private="true">variables.var</File>
    <File Description="Handling of program and test suite">testSuite.c</File>
    <File Description="Auto generated code">autoGeneratedFile.c</File>
    <File Description="Groups test cases for addition">testSet_MyCalcLib_Addition.c</File>
    <File Description="Groups test cases for substraction">testSet_MyCalcLib_Subtraction.c</File>
    <File Description="Groups test cases for multiplication and division">testSet_MyCalcLib_Mult_Div.c</File>
  </Files>
</Program>